### ISSUE TITLE
Img-img retrieval

### ISSUE THREAD

**Issue by epishchik** [marqo-ai/GCL#9]
Hello!

Can your benchmark measure img2img retrieval quality? I assume that if I just change the domains from `[['txt'], ['img']]` to `[['img'], ['img']]` it'll work, but will the metrics be representative?

Tnx in advance.

**Comment by jn2clark** [comment]
Hi @epishchik ! Correct. You can do any combination of text and image, including image to image. As long as the dataset being used is setup for that.
